structure:
    - name: "section"
      type: "macro"
      condition: "<length> > 5"
      ## chapters/ch1-introduction/sec1/broad_intro.tex
      file_name: "chapters/ch[chapter]-[name:chapter]/sec[section]/[name:section].tex"

    - name: "section"
      type: "macro"
      ## chapters/ch1-introduction/sec1.tex
      file_name: "chapters/ch[chapter]-[name:chapter]/sec[section].tex"

    - name: "chapter"
      type: "macro"
      ## chapters/ch1-introduction.tex
      file_name: "chapters/ch[chapter]-[name:chapter].tex"

input:
    folder: "../input"
    main_file: "main.tex"

output:
    folder: "../output"
    main_file: "main.tex"
    figure_folder: "figs"
